version: '3.1'

services:
  api:
    build: ./api
    restart: always
    depends_on:
      - mysql
    ports:
      - "5555:5000"

  mysql:
    image: mysql
    restart: always
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: user
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1

volumes:
  mysql_data: